name: Deploy App
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Syntax # Indispensable pour le point 4 du sujet
        run: php -l index.php

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-projet-amine'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
