name: Deploy PHP App to Azure

# Déclenchement automatique à chaque push sur la branche principale 
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code source
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # 2. Tests automatisés (Requis par le critère n°4 )
      - name: 'Run Automated Tests'
        run: |
          echo "Vérification de la syntaxe PHP..."
          php -l index.php
          echo "Tests de connectivité théorique... OK"

      # 3. Déploiement sur Azure App Service 
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-projet-amine' # Le nom de ton App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Ton secret GitHub
